export const ADD_EVENT = "ADD_EVENT";
export const REPLACE_EVENTS = "REPLACE_EVENTS";
export const CHECK_EVENT = "CHECK_EVENT";
export const UNCHECK_EVENT = "UNCHECK_EVENT";

export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST"
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS"
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE"